/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleZonesRouteImport } from './routes/console.zones'
import { Route as ConsoleTrafficPoliciesRouteImport } from './routes/console.traffic-policies'
import { Route as ConsoleRoute53RouteImport } from './routes/console.route53'
import { Route as ConsoleHealthChecksRouteImport } from './routes/console.health-checks'
import { Route as ConsoleZonesZoneIdRouteImport } from './routes/console.zones.$zoneId'

const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleZonesRoute = ConsoleZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleTrafficPoliciesRoute = ConsoleTrafficPoliciesRouteImport.update({
  id: '/traffic-policies',
  path: '/traffic-policies',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleRoute53Route = ConsoleRoute53RouteImport.update({
  id: '/route53',
  path: '/route53',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleHealthChecksRoute = ConsoleHealthChecksRouteImport.update({
  id: '/health-checks',
  path: '/health-checks',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleZonesZoneIdRoute = ConsoleZonesZoneIdRouteImport.update({
  id: '/$zoneId',
  path: '/$zoneId',
  getParentRoute: () => ConsoleZonesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/console': typeof ConsoleRouteWithChildren
  '/console/health-checks': typeof ConsoleHealthChecksRoute
  '/console/route53': typeof ConsoleRoute53Route
  '/console/traffic-policies': typeof ConsoleTrafficPoliciesRoute
  '/console/zones': typeof ConsoleZonesRouteWithChildren
  '/console/zones/$zoneId': typeof ConsoleZonesZoneIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/console': typeof ConsoleRouteWithChildren
  '/console/health-checks': typeof ConsoleHealthChecksRoute
  '/console/route53': typeof ConsoleRoute53Route
  '/console/traffic-policies': typeof ConsoleTrafficPoliciesRoute
  '/console/zones': typeof ConsoleZonesRouteWithChildren
  '/console/zones/$zoneId': typeof ConsoleZonesZoneIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/console': typeof ConsoleRouteWithChildren
  '/console/health-checks': typeof ConsoleHealthChecksRoute
  '/console/route53': typeof ConsoleRoute53Route
  '/console/traffic-policies': typeof ConsoleTrafficPoliciesRoute
  '/console/zones': typeof ConsoleZonesRouteWithChildren
  '/console/zones/$zoneId': typeof ConsoleZonesZoneIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/console'
    | '/console/health-checks'
    | '/console/route53'
    | '/console/traffic-policies'
    | '/console/zones'
    | '/console/zones/$zoneId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/console'
    | '/console/health-checks'
    | '/console/route53'
    | '/console/traffic-policies'
    | '/console/zones'
    | '/console/zones/$zoneId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/console'
    | '/console/health-checks'
    | '/console/route53'
    | '/console/traffic-policies'
    | '/console/zones'
    | '/console/zones/$zoneId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/zones': {
      id: '/console/zones'
      path: '/zones'
      fullPath: '/console/zones'
      preLoaderRoute: typeof ConsoleZonesRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/traffic-policies': {
      id: '/console/traffic-policies'
      path: '/traffic-policies'
      fullPath: '/console/traffic-policies'
      preLoaderRoute: typeof ConsoleTrafficPoliciesRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/route53': {
      id: '/console/route53'
      path: '/route53'
      fullPath: '/console/route53'
      preLoaderRoute: typeof ConsoleRoute53RouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/health-checks': {
      id: '/console/health-checks'
      path: '/health-checks'
      fullPath: '/console/health-checks'
      preLoaderRoute: typeof ConsoleHealthChecksRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/zones/$zoneId': {
      id: '/console/zones/$zoneId'
      path: '/$zoneId'
      fullPath: '/console/zones/$zoneId'
      preLoaderRoute: typeof ConsoleZonesZoneIdRouteImport
      parentRoute: typeof ConsoleZonesRoute
    }
  }
}

interface ConsoleZonesRouteChildren {
  ConsoleZonesZoneIdRoute: typeof ConsoleZonesZoneIdRoute
}

const ConsoleZonesRouteChildren: ConsoleZonesRouteChildren = {
  ConsoleZonesZoneIdRoute: ConsoleZonesZoneIdRoute,
}

const ConsoleZonesRouteWithChildren = ConsoleZonesRoute._addFileChildren(
  ConsoleZonesRouteChildren,
)

interface ConsoleRouteChildren {
  ConsoleHealthChecksRoute: typeof ConsoleHealthChecksRoute
  ConsoleRoute53Route: typeof ConsoleRoute53Route
  ConsoleTrafficPoliciesRoute: typeof ConsoleTrafficPoliciesRoute
  ConsoleZonesRoute: typeof ConsoleZonesRouteWithChildren
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleHealthChecksRoute: ConsoleHealthChecksRoute,
  ConsoleRoute53Route: ConsoleRoute53Route,
  ConsoleTrafficPoliciesRoute: ConsoleTrafficPoliciesRoute,
  ConsoleZonesRoute: ConsoleZonesRouteWithChildren,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
